CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL NOT NULL,
	uid UUID NOT NULL DEFAULT uuid_generate_v4(),
	domain VARCHAR(63) NOT NULL,
	email VARCHAR(127) NOT NULL,
	password TEXT NULL,
	first_name VARCHAR(127) NOT NULL,
	last_name VARCHAR(127) NOT NULL,
	birth_date DATE NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMPTZ NULL,

	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS users_email_idx ON users USING btree (email);