openapi: 3.0.3
info:
  title: HROOST - OpenAPI 3.0
  description: |-
    HROOST **Internal** API Documentation
  contact:
    email: apiteam@swagger.io
  version: 1.0.0
servers:
  - url: https://example.com
tags:
  - name: Auth
    description: Everything about authentication
paths:
  /auth/login:
    $ref: ./central/auth/auth-login.yaml
  /auth/forgot-password:
    $ref: ./central/auth/auth-forgot-password.yaml
  /auth/password-recovery/check:
    $ref: ./central/auth/auth-password-recovery-check.yaml
  /auth/password:
    $ref: ./central/auth/auth-password.yaml
  /oauth/google/login:
    $ref: ./central/auth/oauth-google-login.yaml
  /oauth/google/callback:
    $ref: ./central/auth/oauth-google-callback.yaml

  # province
  /provinces:
    $ref: ./central/region/province.yaml

components:
  schemas:
    AppID:
      $ref: "./_components/schemas/enum/app-id.yaml"
    RequestValidationErrorCode:
      $ref: "./_components/schemas/enum/request-validation-error-code.yaml"
  parameters:
    Header-X-App-ID:
      in: header
      name: X-App-ID
      required: true
      schema:
        type: string
        enum:
          - internal
        default: web
    Header-User-Agent:
      in: header
      name: User-Agent
      required: true
      schema:
        type: string
        example: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
  responses:
    ResponseInternalServerError:
      $ref: "./_components/responses/internal-server-error.yaml"
  securitySchemes:
    ApiKeyAuth:
      $ref: "./_components/securities/api-key-auth.yaml"
