openapi: 3.0.3
info:
  title: HROOST - OpenAPI 3.0
  description: |-
    HROOST **Mobile** API Documentation
  contact:
    email: apiteam@swagger.io
  version: 1.0.0
servers:
  - url: http://localhost:3001
tags:
  - name: Auth
    description: Everything about authentication
paths:
  # Auth
  /auth/login:
    $ref: ./mobile/auth/auth-login.yaml
  /auth/forgot-password:
    $ref: ./mobile/auth/auth-forgot-password.yaml

  # Region
  /provinces:
    $ref: ./mobile/region/province.yaml

  # Profile
  /profile:
    $ref: ./mobile/profile/profile.yml

  # Attendance
  /attendance:
    $ref: ./mobile/attendance/attendance.yml

components:
  schemas:
    AppID:
      $ref: "./_components/schemas/enum/app-id.yaml"
    RequestValidationErrorCode:
      $ref: "./_components/schemas/enum/request-validation-error-code.yaml"
  parameters:
    Header-User-Agent:
      in: header
      name: User-Agent
      required: true
      schema:
        type: string
        default: Android 13 (33)/Xiaomi M2101K7BNY/User 0.8.0 (80)/in_ID
        example: Android 13 (33)/Xiaomi M2101K7BNY/User 0.8.0 (80)/in_ID
  responses:
    ResponseInternalServerError:
      $ref: "./_components/responses/internal-server-error.yaml"
  securitySchemes:
    ApiKeyAuth:
      $ref: "./_components/securities/api-key-auth.yaml"
    BearerAuth:
      $ref: "./_components/securities/bearer-auth.yaml"
